spring:
  config:
    activate:
      on-profile: default
server:
  port: 8081
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://petclinic-discovery-server-service:8761/eureka/
management:
  zipkin:
    tracing:
      endpoint: http://tracing-server-service:9411/api/v2/spans