spring:
  config:
    activate:
      on-profile: default

server:
  port: 8084
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://petclinic-discovery-server-service:8761/eureka/
management:
  zipkin:
    tracing:
      endpoint: http://tracing-server-service.default.svc.cluster.local:9411/api/v2/spans