server:
  port: 9411

---
spring:
  config:
    activate:
      on-profile: default
eureka:
  client:
    serviceUrl:
      defaultZone: http://tracing-server-service.default.svc.cluster.local:8761/eureka/
