vets:
  cache:
    ttl: 60
    heap-size: 100
spring:
  config:
    activate:
      on-profile: default
server:
  port: 8083
eureka:
  client:
    serviceUrl:
      defaultZone: http://petclinic-discovery-server-service:8761/eureka/
management:
  zipkin:
    tracing:
      endpoint: http://tracing-server:9411/api/v2/spans